spring.application.name=staffhub-backend

# ============================================================
# SQL SERVER DATABASE
# ============================================================

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=StaffHub;integratedSecurity=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ============================================================
# JPA / HIBERNATE
# ============================================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# SERVER
# ============================================================

server.port=8080

