spring.application.name=staffhub-backend

# ============================================================
# DATABASE
# ============================================================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# ============================================================
# JPA / HIBERNATE
# Not used for database table creation.
# Employee CRUD uses JdbcTemplate.
# ============================================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# ============================================================
# SERVER
# ============================================================

server.port=${PORT:8080}